codestates-seb/seb45_main_004

server/src/main/java/com/party/alram/entity/Alarm.java
server/src/main/java/com/party/card/entity/Card.java
server/src/main/java/com/party/chatting/entity/Chatting.java
server/src/main/java/com/party/image/entity/CardImage.java
server/src/main/java/com/party/image/entity/ProfileImage.java
server/src/main/java/com/party/member/entity/Member.java
server/src/main/java/com/party/member/entity/MemberCard.java

entity class 추가 설정

---

server/src/main/java/com/party/auth/fliter/JwtVerificationFilter.java

Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
Object principal = authentication.getPrincipal();
principal.get("member{Id, Nickname, Email}") 해서 원하는거 꺼내쓰시면 됩니당

Authentication으로 사용자정보 가져오기

---

server/src/main/resources/application-server.yml

s3 앤드포인트 주소를 http://celebee-bucket.s3-website.ap-northeast-2.amazonaws.com 으로 수정했습니다

[BE]docs: s3앤드포인트 수정

---

server/src/main/java/com/party/member/dto/MemberCardDto.java
server/src/main/java/com/party/member/dto/MemberCardResponseDto.java
server/src/main/java/com/party/member/dto/MemberResponseDto.java
server/src/main/java/com/party/member/entity/Member.java
server/src/main/java/com/party/member/entity/MemberCard.java
server/src/main/java/com/party/member/mapper/MemberMapper.java

member와 cardlike 연관관계 매핑 완료

---

server/src/main/java/com/party/auth/service/MemberDetailsService.java
server/src/main/java/com/party/card/service/CardService.java
server/src/main/java/com/party/member/mapper/MemberMapper.java
server/src/main/java/com/party/member/service/MemberService.java

반환타입은 Map<String, Object>여서 get(key)로 꺼내오시면 됩니다
예시)
Object memberId = memberService.extractMemberInfo().get("memberId");
memberId -> integer
memberEmail -> string
memberNickname -> string

MemberService에 authentication으로 로그인한 사용자 정보를 받아오는 메서드 추가했습니다

---

server/src/main/java/com/party/member/controller/MemberController.java
server/src/main/java/com/party/member/dto/MemberResponseDto.java
server/src/main/java/com/party/member/entity/Member.java
server/src/main/java/com/party/member/mapper/MemberMapper.java
server/src/main/java/com/party/member/service/MemberService.java

일단 뼈대는 다 만들었어요

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.js
client/src/components/CategoryBtn.js
client/src/index.js
client/src/pages/HomePage.js

-✅ 기능 추가
-✅ UI 작업
-[] 기능 삭제
-[] 에러 관련 수정
feat_FE_Homapgae -> feat_FE
- 페이지 최초 구현
- 카테고리 컴포넌트 구현

[FE] HomePage 구현

---

server/src/main/java/com/party/card/controller/CardController.java
server/src/main/java/com/party/card/dto/CardResponseDto.java
server/src/main/java/com/party/card/mapper/CardMapper.java
server/src/main/java/com/party/card/repository/CardRepository.java
server/src/main/java/com/party/card/service/CardService.java
server/src/main/java/com/party/cardlike/controller/CardLikeController.java
server/src/main/java/com/party/exception/ExceptionCode.java

map, image, 참여중 인원을 제외한 값을 조회할 수 있게 구현했습니다

[BE] feat : 모임글 상세 조회 및 전체 조회 구현

---

client/src/App.css
client/src/pages/InvitePage.js

Feat fe invite page css

---

client/src/App.js
client/src/pages/SignupPage.js

✅ 회원가입 페이지 UI 작업
📍 feat_FE_Signup Page -> feat_FE
페이지 최초 구현

[FE]feat : Signup page 마크업 1차 작성완료

---

server/src/main/java/com/party/board/dto/BoardDto.java

Board post시 response값으로 address값 누락된 건 추가

[BE] feat: Board 생성 시 데이터에 주소값 추가-1

---

server/src/main/java/com/party/board/dto/BoardDto.java
server/src/main/java/com/party/board/service/BoardService.java

Board Entity 클래스와 Dto클래스의 Date 타입을 일치시켰습니다(String -> LocalDate)

[BE]refactor: Date type 일치 시킴

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/pages/HomePage.js
client/src/pages/InvitePage.js

✅ 기능 추가
✅ 추가 UI 작업
📍 feat_FE_Homapage.V2 -> feat_FE
- 추가 css 스타일링 작업
- api 데이터 받아오기 -> 이미지는 be에서 준비되는 데로 진행 예정
- 데이터 최신순 정렬
-

[FE] Hompage 작업 1차 완료

---

client/src/App.js
client/src/pages/HomePage.js

HomePage 카드에 Link 연결 및 InvitePage useParms 적용

feat: HomePage 카드 Link연결 및 InvitePage useParms 적용 

---

server/src/main/java/com/party/board/service/BoardService.java
server/src/main/java/com/party/boardlike/controller/BoardLikeController.java
server/src/main/java/com/party/boardlike/repository/BoardLikeRepository.java
server/src/main/java/com/party/boardlike/service/BoardLikeService.java

제가 작성한 Board 관련 코드들 전체적으로 리팩터링 했습니다

[BE]refactor: Board 구현 코드 리팩터링

---

client/src/components/Button.js
client/src/components/Header.js
client/src/components/LikeIt.js
client/src/components/MyPageTab.js
client/src/components/Participations.js
client/src/components/Profile.js
client/src/pages/MyPage.js

* 추후 추가할 내용
- 서버에 유저데이터를 요청하여 참여한 목록 과 찜한 목록 불러오기
- 로그인 상태를 반영하여 내 정보를 볼때(편집기능o)와 타 유저의 정보를 볼 때(편집기능 x) 의 차이 구현
Issue: #16

유저정보 조회페이지 구현

---

client/package-lock.json
client/package.json
client/src/pages/HomePage.js

✅ 기능 추가
✅ 추가 UI 작업
📍 feat_FE_Homapage.V3 -> feat_FE
- 추가 css 스타일링 작업
- api 데이터 무한 스크롤 구현중 (미완료)

[FE]feat : 무한 스크롤 구현중

---

client/src/App.css
client/src/App.js
client/src/pages/HomePage.js
client/src/pages/InvitePage.js

HomepPage, InvitePage 페이지의 양옆 margin 값 추가
app.css 기본 스타일 수정

style: 각 페이지 margin 수정

---

client/src/pages/HomePage.js

✅ 기능 수정
📍 feat_FE_Homapage.V4 -> feat_FE
- api 데이터 최신순 정렬 수정

[FE]feat:api 데이터 최신순정렬 수정

---

server/src/main/java/com/party/board/controller/BoardController.java
server/src/main/java/com/party/board/entity/Board.java
server/src/main/java/com/party/board/repository/BoardRepository.java
server/src/main/java/com/party/board/service/BoardService.java

BoardCategory Enum 식별자를 문자에서 숫자로 변경했습니다
ex) CATEGORY_LEISURE("LEISURE") >CATEGORY_LEISURE(1)
이유 : GET 요청 시 문자형관련 에러이슈 발생(NumberFormatException)
API 수정 완료

[BE]feat: 특정 카테고리별로 모임글 조회 기능 구현

---

server/build.gradle
server/src/main/java/com/party/config/AwsS3Config.java
server/src/main/resources/application-local.yml
server/src/main/resources/application-server.yml

AWS 버킷과 연결을 위해 관련된 설정을 추가하였습니다.

[BE]feat:AWS 연결 관련 설정 추가

---

server/src/main/java/com/party/board/controller/BoardController.java
server/src/main/java/com/party/board/repository/BoardRepository.java
server/src/main/java/com/party/board/service/BoardService.java

모집 글 전체 조회(최신순) -디폴트 값
모집 글 전체 조회(좋아요순)
특정 카테고리 별 조회(최신순)
특정 카테고리 별 조회(좋아요순)
기능 추가했습니다
API 수정 완료

[BE]feat: 카테고리별 좋아요 순 조회 기능 구현

---

client/src/pages/HomePage.js

✅ 기능 수정
📍 feat_FE_Homapage.V5 -> feat_FE
- 무한 스크롤 1차 구현 (미완성)

[FE] Homepage 무한 스크롤 1차 구현

---

.idea/misc.xml
.idea/seb45_main_004.iml
server/src/main/java/com/party/board/controller/BoardController.java
server/src/main/java/com/party/board/repository/BoardRepository.java
server/src/main/java/com/party/board/service/BoardService.java

전체글 검색
카테고리별 검색
본문내용도 검색가능하게 했습니다
API 수정 예정

[BE]feat: 검색 기능 구현(카테고리별,본문 검색 가능)

---

client/src/App.js
client/src/components/Header.js
client/src/pages/SignupPage.js

✅ 기능 추가(회원가입 요청 보내기)
✅ 추가 UI 작업 (상세 작업)
📍 feat_FE_Signuppage.V2-> feat_FE
- 회원가입 요청 보내기
- 추가 css 작업 (폰트, 규격 등)

[FE] Signup Page 기능 구현 및 css 작업

---

client/src/pages/HomePage.js

✅ UI 수정
📍 feat_FE_Homepage.V6-> feat_FE
- 검색창 css 수정

[FE]style : 검색창 css 수정

---

server/src/main/resources/application.yml

[BE]fix: 빌드 안 되는 버그 수정

---

client/src/components/CategoryBtn.js
client/src/components/CategoryMappings.js
client/src/pages/HomePage.js
client/src/pages/SignupPage.js
client/src/services/MapKakao.js

✅ 기능 추가
✅ 추가 UI 작업
📍 feat_FE_Homepage.V7-> feat_FE
- 카테고리별 필터링 구현
- Homepage, signuppage 추가 css 작업 (input,button창 수정)

[FE] Homepage 카테고리별 필터링 구현 완료

---

server/src/main/java/com/party/board/dto/BoardResponseDto.java
server/src/main/java/com/party/board/mapper/BoardMapper.java

모임 글 상세 조회 시 작성자의 프로필을 조회할 수 있도록 기능 추가했습니다.

[BE]feat:모임 글 조회 시 작성자 유저 프로필 조회되도록 추가

---

server/src/main/java/com/party/board/controller/ApplicantController.java
server/src/main/java/com/party/board/dto/ApplicantResponseDto.java
server/src/main/java/com/party/board/dto/BoardDto.java
server/src/main/java/com/party/board/entity/Applicant.java
server/src/main/java/com/party/board/mapper/ApplicantMapper.java
server/src/main/java/com/party/board/repository/ApplicantRepository.java
server/src/main/java/com/party/board/service/ApplicantService.java
server/src/main/java/com/party/board/service/BoardService.java

모임 글 상세 조회 시 모든 참여자의 이미지 정보를 가져올 수 있도록 추가 구현

[BE]feat:모임 글 조회 시 참여한 사람 이미지정보를 가져올 수 있도록 추가

---

server/src/main/resources/application-local.yml
server/src/main/resources/application-server.yml
server/src/main/resources/application.yml

[BE]docs: 카카오 로그인 redirect 링크 변경

---

client/src/pages/HomePage.js

✅ 기능 추가
✅ 추가 UI 작업
📍 feat_FE_Homepage.V8-> feat_FE
- 검색 기능 구현
- 좋아요순 조회 (ALL만)
- 카테고리 버튼 css

[FE] Homepage 기능 구현 및 추가 CSS

---

client/src/pages/HomePage.js

✅ 기능 추가
✅ 추가 UI 작업
📍 feat_FE_Homepage.V9-> feat_FE
- 카테고리별 검색 기능 구현
- 카테고리별 좋아요순 조회 
- 좋아요순서 버튼 css 작업
- 헤더 css 작업(애니메이션 효과주기)

[FE] Homepage 기능 구현 및 CSS

---

server/src/main/resources/application-server.yml

[BE]docs: kakao redirect url 변경
서버부분만 변경되었습니다.

[BE]docs: kakao redirect url 변경

---

server/src/main/java/com/party/image/controller/ImageController.java
server/src/main/java/com/party/image/service/AwsService.java

디렉토리 내 파일 개수가 다른 것에 대응하기 위해 S3 이미지 URL조회 로직 리펙토링 작업했습니다.

[BE]refactor:S3 이미지 URL조회 로직 리펙토링

---

server/src/main/java/com/party/member/controller/MemberController.java
server/src/main/java/com/party/member/dto/MemberPatchDto.java
server/src/main/java/com/party/member/repository/MemberRepository.java
server/src/main/java/com/party/member/service/MemberService.java

[BE]refactor: 회원정보 수정 삭제 조회시 필요한 엔드포인트 주소 email로 변경
빌드테스트: 완료

[BE]refactor: 회원정보 수정 삭제 조회시 필요한 엔드포인트 주소 email로 변경

---

client/src/api/api.js
client/src/components/EmailLoginForm.js
client/src/components/Header.js
client/src/index.js
client/src/pages/LoginPage.js
client/src/redux/actionTypes.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/store.js

- 로그인 데이터 post 시 토큰값 성공적으로 받아옴
- 받아온 토큰값을 로컬 스토리지에 저장함
- 로그인 상태관리 리덕스로 작성함
- 보완해야 할 사항
- 로그인 상태관리를 리덕스로 작성하였으나, 코드가 어지러워짐...
- 로그인 상태에 따라 헤더가 변하긴 하는데, 로그인 하는 즉시 변하지 않음.. 
issue : #28

{FE]로그인 기능 구현

---

server/src/main/java/com/party/member/dto/MemberPatchDto.java

[BE]fix: 회원정보 수정시 id 값 변경으로 인한 오류 출력 수정

[BE]fix: 회원정보 수정시 id 값 변경으로 인한 오류 출력 수정

---

client/src/pages/HomePage.js

✅ UI 작업
📍 feat_FE_Homepage.V11-> feat_FE
- 초대장 title에서 이미지로 불러오기
- 초대장 이미지 css 작업

[FE] Homepage 초대장 이미지로 구현

---

client/src/components/OauthLoginButton.js

✅ 기능 추가
📍 feat_FE_KakaoOAuth-> feat_FE
- 카카오 OAuth 관련 링크 연결 (카카오 서버로 연결은 성공)
- 백엔드 서버와 통신은 아직 x

[FE] 카카오 OAuth 링크 연결

---

server/src/main/java/com/party/member/controller/MemberController.java
server/src/main/java/com/party/member/dto/MemberPatchDto.java

[BE]refactor: 회원정보 수정시 email값 설정 방식변경
memberpatchdto에 email 필드 삭제하였습니다

[BE]refactor: 회원정보 수정시 email값 설정 방식변경

---

client/src/pages/SignupPage.js

✅ 기능 추가
📍 feat_FE_SignupPage.V3-> feat_FE
- 회원가입 유효성 검사

[FE] Signup page 유효성 검사 구현

---

client/src/pages/HomePage.js
client/src/pages/LoginPage.js
client/src/pages/SignupPage.js

✅ 기능 코드 내용 수정
📍 feat_FE_Modify-> feat_FE
- 로그인,회원가입 유효성 검사 코드 일부 수정
- 메인 전체 좋아요순 코드 수정

[FE] 일부 코드 수정 (로그인,회원가입,메인)

---

server/src/main/java/com/party/board/entity/Board.java
server/src/main/java/com/party/board/repository/BoardRepository.java

[BE]refactor: Board Entity에서 totalNum, money 음수 값 선택 못하게 수정했습니다.
date 이미 지난 날짜는 선택 못하게 수정했습니다. 
getBoard 시 발생하는 N+1 문제 해결했습니다.(fetch join사용)

[BE]refactor : Board Entity 수정 및 N+1 문제 해결

---

server/src/main/java/com/party/member/dto/MemberBoardLikeResponseDto.java
server/src/main/java/com/party/member/mapper/MemberMapper.java

[BE]feat: member 정보 조회시 좋아요한 보드의 id와 이미지 반환되게 설정
빌드테스트: 완료

[BE]feat: member 정보 조회시 좋아요한 보드의 id와 이미지 반환되게 설정

---

server/src/main/java/com/party/auth/config/SecurityConfiguration.java
server/src/main/java/com/party/member/controller/MemberController.java
server/src/main/java/com/party/member/dto/MemberBoardLikeResponseDto.java
server/src/main/java/com/party/member/dto/MemberResponseDto.java
server/src/main/java/com/party/member/dto/SimpleMemberResponseDto.java
server/src/main/java/com/party/member/entity/Member.java
server/src/main/java/com/party/member/mapper/MemberMapper.java
server/src/main/java/com/party/member/repository/MemberRepository.java
server/src/main/java/com/party/member/service/MemberService.java

[BE]feat: 전체 회원의 id email nickname 을 조회가능한 메서드 작성
[BE]feat: 로그아웃 endpoint작성
[BE]feat: 멤버 조회시 팔로우와 팔로워 숫자도 같이 응답
빌드테스트 완료

[BE]feat: 전체 회원의 id email nickname 을 조회가능한 메서드 작성, 로그아웃 endpoint 작성 멤버 조회시 팔로우와 팔로워 숫자도 같이 응답

---

client/src/App.js
client/src/components/EmailLoginForm.js
client/src/components/Header.js
client/src/pages/LoginPage.js
client/src/pages/MyPage.js
client/src/redux/actionTypes.js
client/src/redux/actions.js
client/src/redux/reducers.js

1. 로그인 상태에 따른 헤더 버튼 변화 성공함
2. 로그인 성공 시 받은 응답헤더에 멤버 아이디를 상태값으로 저장하여 마이페이지 유저 데이터 요청 시 엔드포인트로 사용함

[FE] 로그인 상태에 따른 헤더 변화 구현 및 유저 데이터 불러와서 프로필 렌더링 성공

---

client/src/pages/HomePage.js

✅ UI 작업
📍 feat_FE_Homepage.V12-> feat_FE
- hover시 타이틀과 좋아요가 표시되게 css 수정

[FE] Homepage : hover시 타이틀과 좋아요 표시

---

.idea/misc.xml

[BE]fix: misc.xml 충돌해결
이전 내용으로 변경

[BE]fix: misc.xml 충돌해결

---

server/src/main/java/com/party/auth/service/OAuthService.java

[BE]fix: 카카오 로그인 관련 jwt 오류 수정 완료
jwt토큰 불일치 문제로 인한 멤버삭제 불가능 오류 해결

[BE]fix: 카카오 로그인 관련 jwt 오류 수정 완료

---

.idea/gradle.xml
server/build.gradle
server/src/main/java/com/party/follow/controller/FollowController.java
server/src/main/java/com/party/follow/service/FollowService.java
server/src/main/java/com/party/mail/config/AsyncConfig.java
server/src/main/java/com/party/mail/handler/MailHandler.java
server/src/main/java/com/party/mail/service/MailService.java
server/src/main/resources/application.yml

누군가 본인을 팔로우 시 팔로우 알림 이메일을 전송합니다
지연 문제는 비동기 처리

[BE]feat: 팔로우 시 알림 이메일 전송 기능 구현

---

server/src/main/java/com/party/member/dto/MemberPostDto.java

[BE]feat: 회원가입시 비밀번호가 8자 이상이여야 가입되게 변경
MemberPostDto에 @Pattern 추가했습니다

[BE]feat: 회원가입시 비밀번호가 8자 이상이여야 가입되게 변경

---

server/src/main/java/com/party/auth/config/SecurityConfiguration.java
server/src/main/java/com/party/auth/controller/OAuthController.java
server/src/main/java/com/party/auth/dto/Refresh.java
server/src/main/java/com/party/auth/fliter/JwtAuthenticationFilter.java
server/src/main/java/com/party/auth/service/OAuthService.java
server/src/main/java/com/party/member/entity/Member.java
server/src/main/java/com/party/member/repository/MemberRepository.java
server/src/main/java/com/party/member/service/MemberService.java

엑세스 토큰 만료시 리프레쉬 토큰을 이용해서(만료되지 않았다면) 엑세스 토큰과 리프레쉬 토큰을 재발급 받게 해주는 코드 작성

[BE]feat: 리프레쉬 토큰을 이용해서 엑세스 토큰 재발급 가능한 코드 작성

---

server/src/main/resources/application-server.yml
server/src/main/resources/application.yml

[BE]feat: server 카카오 redirect url 변경
http://localhost:3000/oauth/kakao/login -> 카카오로그인 관련 url변경

[BE]feat: server 카카오 redirect url 변경

---

client/src/App.js
client/src/components/OauthLoginButton.js
client/src/pages/KakaoRedirect.js
client/src/pages/SignupPage.js

✅ 기능 추가
📍 feat_FE_KakaoOAuth.V2-> feat_FE
- 카카오 OAuth 서버 완료
- 백엔드에 인가코드 넘겨주기 완료
- 하루 모임페이지에서 로그인까지 구현 완료

[FE] 카카오 OAuth 구현 완료

---

client/src/pages/HomePage.js

✅ UI 작업
📍 feat_FE_Homepage.V14-> feat_FE
- 서비스 소개 css 수정

[FE] Homepage 서비스 소개 css 수정

---

server/src/main/java/com/party/ServerApplication.java
server/src/main/java/com/party/board/entity/Applicant.java
server/src/main/java/com/party/board/entity/Board.java
server/src/main/java/com/party/board/repository/ApplicantRepository.java
server/src/main/java/com/party/board/repository/BoardRepository.java
server/src/main/java/com/party/board/service/BoardService.java
server/src/main/java/com/party/follow/service/FollowService.java
server/src/main/java/com/party/mail/service/MailService.java

모임 하루전 오전 10시에 참여자들에게 D-1알림 이메일이 발송되는 기능입니다
그 외 수정 사항)  
-Applicant Entity Id를 id로 수정
-Board Entity createdAt 칼럼 삭제

[BE]feat: 모임 하루 전 알림이메일 전송 기능 구현

---

server/src/main/java/com/party/alram/Controller/AlarmController.java
server/src/main/java/com/party/alram/dto/AlarmResponse.java
server/src/main/java/com/party/alram/entity/Alarm.java
server/src/main/java/com/party/alram/repository/AlarmRepository.java
server/src/main/java/com/party/alram/repository/EmitterRepository.java
server/src/main/java/com/party/alram/repository/EmitterRepositoryImpl.java
server/src/main/java/com/party/alram/service/AlarmService.java
server/src/main/java/com/party/board/service/ApplicantService.java
server/src/main/java/com/party/board/service/BoardService.java

- 알림기능 MVC 작업 완료
- 클라에서 구독 요청 시 emitter 저장 구현
- 모임 글 작성 시 알림 전송
- 모임 참여 시 작성자에게 알림 전송

[BE]feat: 알림기능 MVC 작업

---

server/src/main/java/com/party/alram/Controller/AlarmController.java
server/src/main/java/com/party/board/service/ApplicantService.java
server/src/main/java/com/party/board/service/BoardService.java

- 글 작성 시 알림
- 모임 참여 시 알림 (작성자, 참여자 둘다에게)
내용 추가했습니다

[BE]feat:알림 내용 추가

---

server/src/main/java/com/party/ServerApplication.java
server/src/main/java/com/party/board/service/ApplicantService.java
server/src/main/java/com/party/board/service/BoardService.java

- 매일 00시 기준 날짜 지난 모임 마감처리
- totalNum = currentNum 일 시 마감처리

[BE]feat:날짜지난 모임 마감처리, 인원수 충족 시 마감처리 구현 

---

server/src/main/java/com/party/auth/controller/OAuthController.java
server/src/main/java/com/party/auth/service/OAuthService.java
server/src/main/java/com/party/exception/ExceptionCode.java
server/src/main/java/com/party/member/repository/MemberRepository.java

refreshToken을 이용한 AccessToken, RefreshToken 재발급 코드 작성완료
재발급시 재발급된 RefreshToken Member 데이터베이스 테이블에 저장

[BE]feat: 클라이언트의 refresh 토큰이 DB의 토큰과 맞는지 검증하는 과정 추가

---

server/src/main/java/com/party/board/entity/Board.java

모집글 작성 시 오늘 날짜로부터 2일후의 날짜부터 작성 할 수 있습니다

[BE]refactor: 모집날짜는 오늘날짜로부터 2일후부터 선택 가능

---

client/src/pages/KakaoRedirect.js
client/src/pages/SignupPage.js

✅ UI 작업
📍 feat_FE_KakaoRedirectPage-> feat_FE
- 카카오 리다이렉트 페이지 UI 작업

[FE] Kakao 리다이렉트 페이지 css 수정

---

server/src/main/java/com/party/alram/Controller/AlarmController.java
server/src/main/java/com/party/alram/dto/AlarmMapper.java
server/src/main/java/com/party/alram/dto/AlarmResponseDto.java
server/src/main/java/com/party/alram/entity/Alarm.java
server/src/main/java/com/party/alram/repository/AlarmRepository.java
server/src/main/java/com/party/alram/service/AlarmService.java
server/src/main/java/com/party/board/entity/Board.java
server/src/main/java/com/party/board/service/ApplicantService.java
server/src/main/java/com/party/board/service/BoardService.java
server/src/main/java/com/party/member/entity/Member.java
server/src/main/resources/application-server.yml

- 특정 멤버가 가진 모든 알림 가져오기 기능 
- 특정 멤버의 알림 모두 삭제 기능 
구현 완료했습니다

[BE]feat:특정 멤버모든 알림 GET, 알림 모두 삭제 기능 구현

---

server/build.gradle
server/src/main/java/com/party/chatting/config/WebSockConfig.java
server/src/main/java/com/party/member/controller/MemberController.java

members/me 로 토큰을 보내면 토큰의 유저 정보를 리턴합니다

[BE]feat: members/me 로 토큰의 주인 정보를 리턴하는 엔드포인트 추가

---

client/public/index.html
client/src/App.js
client/src/components/Header.js
client/src/components/Profile.js
client/src/pages/InvitePage.js
client/src/pages/LoginPage.js
client/src/pages/UserPage.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/services/ShareKakao.js

- members/me 엔드포인트 서버담당자에게 요청하여 생성하였으며, 마이페이지를 me 엔드포인트에 연결함
- 게시물 내에서 작성자 이미지 클릭시 작성자의 프로필이 렌더링되는 페이지는 유저페이지로 분리하여, members/memberid에 연결함

[FE]feat: 마이페이지와 유저페이지를 분리하였으며, 게시글에서 작성자 이미지 클릭 시 해당 작성자의 프로필이 렌더링됨

---

client/src/components/Header.js

✅ 기능 수정
📍 feat_FE_headr-token-> feat_FE
- 페이지 새로 고침시 헤더 로그아웃되는 현상 해결 완료

[FE] Header 새로 고침 이슈 해결

---

client/src/components/Button.js
client/src/components/Profile.js
client/src/pages/KakaoRedirect.js
client/src/pages/MyPage.js

- 카카오 로그인 시 응답 헤더의 멤버 아이디 전역 상태 값에 저장하기
- 로그인된 유저의 마이페이지에서만 편집 버튼이 렌더링될수 있도록 수정

[FE]fix: 마이페이지 편집 기능 관련 코드 수정

---

client/src/components/Button.js
client/src/components/EmailLoginForm.js
client/src/components/OauthLoginButton.js
client/src/pages/LoginPage.js
client/src/pages/SignupPage.js

✅ UI 수정
📍 feat_FE_Markup-> feat_FE
- 로그인, 회원가입 페이지 통일성 있게 구현

[FE] style : 로그인, 회원가입 페이지 css 수정

---

server/src/main/resources/application-server.yml

[BE]docs: 카카오 redirect URL 수정
URL 수정입니다!

[BE]docs: 카카오 redirect URL 수정

---

client/src/components/OauthLoginButton.js

✅ 카카오 리다이렉트 수정
📍 feat_FE_KakaoOauth-> feat_FE
- 카카오 리다이렉트 주소 수정

[FE] 카카오 URL 수정

---

client/src/pages/HomePage.js

✅ 마크업 작업
📍 feat_FE_Homepage.V15-> feat_FE
- 마진,패딩 값 맞추기
- 반응형 작업을 위해 미디어 쿼리 추가

[FE] Homepage CSS추가

---

client/src/pages/SignupPage.js

✅ 멘트 수정
📍 feat_FE_Signuppage.V4-> feat_FE
- 동의 체크박스 멘트 수정

[FE] Signup page 동의 체크박스 멘트 수정

---

server/src/main/java/com/party/member/controller/MemberController.java

남의 마이페이지에만 적용해서 본인의 마이페이지에도 적용햇습니다

[BE]feat: me 엔드포인트에도 정렬기능 추가

---

server/src/main/java/com/party/member/mapper/MemberMapper.java

[BE]fix: 참여한 모임목록 조회시 closed 표시 안 되던 현상 수정

---

client/src/components/OauthLoginButton.js
client/src/pages/KakaoRedirect.js

✅ 스타일 추가
📍 feat_FE_Homepage.V16-> feat_FE
- 카카오 회원가입시 알럿창 추가

[FE] 카카오 로그인시 알럿창 추가

---

client/src/pages/KakaoRedirect.js

✅ 버그 수정
📍 feat_FE_KakaoRedirect-> feat_FE
- 카카오 버그 수정

[FE] KakaoRedirect 버그 수정

---

server/src/main/java/com/party/member/controller/MemberController.java

[BE]fix: 참여한 모임목록 조회시 closed 표시가 제일 앞으로 나오는 현상 수정
마이페이지 및 타인의 페이지 조회시 정렬 반대로 되는 현상 수정

[BE]fix: 참여한 모임목록 조회시 closed 표시가 제일 앞으로 나오는 현상 수정

---

client/src/components/MyProfile.js

[FE]에딧버튼 렌더링 및 패치 요청 가능하도록 수정함

---

client/src/components/IsLoginAvatar.js
client/src/components/MyProfile.js
client/src/pages/InvitePage.js

- 모달 내 이미지 위에 마우스 호버 시 포인터 모양 변경
- 자기소개글 1자 미만 20자 초과 시 경고창 띄우기
- 초대장 상세페이지에서 호스트/ 참여자 이미지 클릭 시 해당 유저의 페이지로 이동
- ex 로그인한 유저와 게시글 호스트(참여자)가 같은 경우 -> 로그인한 유저의 마이페이지로 이동(편집 기능 사용가능)
- ex 로그인한 유저와 게시글 호스트(참여자)가 다른 경우 -> 해당 게시글 호스트(참여자)의 페이지로 이동(편집 기능 x, 팔로우 기능 -구현예정)
- ex 로그인하지 않은 상태인 경우 -> 해당 게시글 호스트(참여자) 페이지로 이동(편집 기능x, 팔로우 기능 - 구현예정)

[FE] 모달 내 포인터 스타일 변경, 자기 소개글, 유저 페이지 이동 이슈 등

---

client/src/components/OauthLoginButton.js
client/src/pages/HomePage.js

✅ 버그 수정
📍 feat_FE_Homepage.V17-> feat_FE
- 카카오 리다이렉트 페이지 변경
- 버그 관련 내용 수정

[FE] 버그 수정 및 카카오 리다이렉트 페이지 변경

---

client/src/App.css
client/src/components/Header.js
client/src/components/IsLoginAvatar.js
client/src/components/LikeIt.js
client/src/components/MemberProfile.js
client/src/components/MyPageTab.js
client/src/components/MyProfile.js
client/src/components/NotLoginAvatar.js
client/src/components/Participations.js
client/src/pages/MyPage.js
client/src/pages/UserPage.js

- 마이(유저)페이지 css 작업 진행 - 반응형 웹 적용
- 로그아웃 시 서비스 사용 중 로컬 스토리지에 저장되는 데이터 삭제 코드 작성

[FE] 마이(유저)페이지 CSS 작업, 로그아웃 시 로컬 스토리지 내 데이터 삭제 등

---

server/src/main/java/com/party/auth/config/SecurityConfiguration.java
server/src/main/java/com/party/member/controller/MemberController.java

[BE]feat: http -> https로 리다이렉트 해주는 설정 추가
http
.requiresChannel()
.requestMatchers(r -> r.getHeader("X-Forwarded-Proto") != null)
.requiresSecure();

[BE]feat: http -> https로 리다이렉트 해주는 설정 추가

---

client/src/pages/HomePage.js
client/src/pages/KakaoRedirect.js
client/src/pages/SignupPage.js

✅ api 수정
📍 feat_FE_API> feat_FE
- API 수정 (홈페이지, 회원가입, 카카오 로그인)

[FE] API 수정

---

client/src/pages/KakaoRedirect.js

✅ api 수정
📍 feat_FE_kakao_api> feat_FE
- API 수정

[FE] fix : 카카오 api 수정

---

server/src/main/java/com/party/auth/config/SecurityConfiguration.java

[BE]feat: 로그인 하지 않은 사용자가 members/me 진입 못하게 수정

[BE]feat: 로그인 하지 않은 사용자가 members/me 진입 못하게 수정

---

server/src/main/java/com/party/auth/config/SecurityConfiguration.java

[BE]fix: 로그인 하지 않은 사용자가 members/me 진입 못하게 수정 post -> get 으로 수정

---

client/src/pages/HomePage.js

✅ 버그 수정
📍 feat_FE_infinite> feat_FE
###업데이트 사항
- 무한 스크롤 버그 수정

[FE]fix : 무한스크롤 버그 수정

---

server/src/main/java/com/party/auth/config/SecurityConfiguration.java
server/src/main/java/com/party/auth/service/OAuthService.java
server/src/main/java/com/party/exception/ExceptionCode.java
server/src/main/java/com/party/exception/GlobalExceptionHandler.java
server/src/main/java/com/party/member/service/MemberService.java

닉네임 중복시 409, 이메일중복시 410 상태코드를 보내주게 변경
에러 내용도 응답으로 간단하게 갑니다

[BE]feat: 닉네임 중복시 409, 이메일중복시 410 상태코드를 보내주게 변경

---

server/src/main/java/com/party/auth/service/OAuthService.java
server/src/main/java/com/party/exception/ExceptionCode.java
server/src/main/java/com/party/exception/GlobalExceptionHandler.java
server/src/main/java/com/party/member/service/MemberService.java

Revert "[BE]feat: 닉네임 중복시 409, 이메일중복시 410 상태코드를 보내주게 변경"

---

client/src/components/Button.js
client/src/pages/HomePage.js
client/src/pages/LoginPage.js
client/src/pages/SignupPage.js

✅ style 수정
📍 feat_FE_last> feat_FE
- css 작업

[FE] style : css 수정

---

client/src/pages/SignupPage.js

✅ 오타 수정
📍 feat_FE_homepage_english -> feat_FE
- 영어 수정

[FE] homepage 영어 수정

---

server/Dockerfile

- Dockerfile 프로퍼티 설정 추가
- logback 파일 재설정

fix: Dockerfile 프로퍼티 설정 추가

---

server/Dockerfile

Reverts codestates-seb/seb45_main_004#368
브렌치 설정을 잘못해서 다시 복구합니다

Revert "fix: Dockerfile 프로퍼티 설정 추가"
